"""Export metrics JSON and a simple HTML decision report."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ab_test.scorecard import Scorecard


def write_metrics_json(metrics: dict[str, Any], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        **metrics,
    }
    path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    return path


def write_html_report(scorecard: Scorecard, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    m = scorecard.metrics
    rows = "\n".join(
        f"<tr><td>{g['gate']}</td><td><b>{g['status']}</b></td><td>{g['detail']}</td></tr>"
        for g in scorecard.gates
    )
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>A/B Experiment Decision Report</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem; max-width: 960px; color: #1a1a1a; }}
    h1 {{ margin-bottom: 0.2rem; }}
    .muted {{ color: #555; }}
    .rec {{ font-size: 1.4rem; padding: 0.75rem 1rem; background: #f4f6f8; border-left: 4px solid #c45c26; }}
    table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
    th, td {{ border: 1px solid #ddd; padding: 0.5rem 0.6rem; text-align: left; vertical-align: top; }}
    th {{ background: #f0f0f0; }}
    code {{ background: #f5f5f5; padding: 0.1rem 0.3rem; }}
  </style>
</head>
<body>
  <h1>Marketing campaign landing page — experiment decision</h1>
  <p class="muted">Generated by advanced production pipeline (v3). Baseline notebook remains unchanged for learning.</p>
  <div class="rec"><strong>Recommendation: {scorecard.recommendation}</strong><br/>{scorecard.reason}</div>
  <h2>Key metrics</h2>
  <ul>
    <li>Control rate: <code>{m.get('p_control', float('nan')):.4%}</code></li>
    <li>Treatment rate: <code>{m.get('p_treatment', float('nan')):.4%}</code></li>
    <li>Lift (new − old): <code>{m.get('diff', float('nan')) * 100:.4f} pp</code></li>
    <li>z / p: <code>{m.get('zstat', float('nan')):.4f}</code> / <code>{m.get('pvalue', float('nan')):.6f}</code></li>
    <li>Analytic 95% CI: <code>[{m.get('ci_low', float('nan')):.6f}, {m.get('ci_high', float('nan')):.6f}]</code></li>
    <li>Bootstrap 95% CI: <code>[{m.get('bootstrap_ci_low', float('nan')):.6f}, {m.get('bootstrap_ci_high', float('nan')):.6f}]</code></li>
    <li>SRM p / imbalance: <code>{m.get('srm_pvalue', float('nan')):.6g}</code> / <code>{m.get('srm_imbalance_pp', float('nan')):.4f} pp</code></li>
    <li>TOST equivalent (± practical band): <code>{m.get('tost_equivalent')}</code></li>
    <li>Bayesian P(new &gt; old): <code>{m.get('bayes_p_new_better', float('nan')):.2%}</code></li>
    <li>ITT agreement: <code>{m.get('itt_agreement')}</code> ({m.get('itt_detail', '')})</li>
    <li>Power @ +1 pp MDE: <code>{m.get('power_mde', float('nan')):.1%}</code></li>
  </ul>
  <h2>Scorecard gates</h2>
  <table>
    <thead><tr><th>Gate</th><th>Status</th><th>Detail</th></tr></thead>
    <tbody>
      {rows}
    </tbody>
  </table>
  <p class="muted">Inferential statistics only — not predictive ML. Null / HOLD outcomes are valid production results.</p>
</body>
</html>
"""
    path.write_text(html, encoding="utf-8")
    return path
